# Generated by Django 5.1.6 on 2026-09-01 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gebeurtenis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tijdstip', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('soort', models.CharField(choices=[('login', 'Inloggen'), ('login_mislukt', 'Inloggen mislukt'), ('mfa', 'Tweede factor'), ('mfa_mislukt', 'Tweede factor mislukt'), ('sso', 'SSO-login'), ('sso_mislukt', 'SSO-login mislukt'), ('uitloggen', 'Uitloggen'), ('wijziging', 'Wijziging in een component'), ('verbinding', 'Verbindingsbeheer'), ('instelling', 'Instelling gewijzigd')], db_index=True, max_length=32)),
                ('gebruikersnaam', models.CharField(blank=True, default='', max_length=150)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('omgeving', models.CharField(blank=True, default='', max_length=100)),
                ('component', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('resource', models.CharField(blank=True, default='', max_length=64)),
                ('actie', models.CharField(blank=True, default='', max_length=32)),
                ('doel', models.CharField(blank=True, default='', max_length=500)),
                ('gelukt', models.BooleanField(default=True)),
                ('detail', models.TextField(blank=True, default='')),
                ('gebruiker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'gebeurtenis',
                'verbose_name_plural': 'gebeurtenissen',
                'ordering': ('-tijdstip',),
                'indexes': [models.Index(fields=['-tijdstip', 'soort'], name='auditlog_ge_tijdsti_8ff78e_idx')],
            },
        ),
    ]
