# Generated by Django 5.1.6 on 2026-09-01 19:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Omgeving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=60, unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9][a-z0-9-]*$', 'Alleen kleine letters, cijfers en koppeltekens.')])),
                ('domein', models.CharField(blank=True, default='', help_text="Basisdomein, bijvoorbeeld 'gemeente.nl'. Gebruikt bij automatisch zoeken.", max_length=200)),
                ('opmerking', models.TextField(blank=True, default='')),
                ('is_standaard', models.BooleanField(default=False, help_text='Wordt geopend als er geen omgeving gekozen is.')),
                ('aangemaakt_op', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'omgeving',
                'verbose_name_plural': 'omgevingen',
                'ordering': ('naam',),
            },
        ),
        migrations.CreateModel(
            name='Verbinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(help_text="Sleutel uit de componentregistry, bijvoorbeeld 'openzaak'.", max_length=64)),
                ('basis_url', models.URLField(help_text='Zonder API-pad, bijvoorbeeld https://openzaak.gemeente.nl', max_length=500)),
                ('actief', models.BooleanField(default=True)),
                ('auth_type', models.CharField(choices=[('zgw-jwt', 'ZGW-JWT (client-id + secret)'), ('token', 'Statisch token in de Authorization-header'), ('sessie', 'Sessie-login (gebruikersnaam + wachtwoord)'), ('geen', 'Geen authenticatie')], default='zgw-jwt', max_length=16)),
                ('client_id', models.CharField(blank=True, default='', max_length=200)),
                ('secret_versleuteld', models.CharField(blank=True, default='', max_length=1024)),
                ('token_versleuteld', models.CharField(blank=True, default='', max_length=2048)),
                ('token_prefix', models.CharField(default='Token', help_text="Voorvoegsel in de Authorization-header. De meeste Maykin-componenten gebruiken 'Token', sommige 'Bearer'. De verbindingstest stelt dit zo nodig zelf bij.", max_length=20)),
                ('gebruikersnaam', models.CharField(blank=True, default='', max_length=200)),
                ('wachtwoord_versleuteld', models.CharField(blank=True, default='', max_length=1024)),
                ('laatste_test_op', models.DateTimeField(blank=True, null=True)),
                ('laatste_test_ok', models.BooleanField(blank=True, null=True)),
                ('laatste_test_melding', models.TextField(blank=True, default='')),
                ('omgeving', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verbindingen', to='verbindingen.omgeving')),
            ],
            options={
                'verbose_name': 'verbinding',
                'verbose_name_plural': 'verbindingen',
                'ordering': ('omgeving__naam', 'component'),
                'constraints': [models.UniqueConstraint(fields=('omgeving', 'component'), name='uniek_component_per_omgeving')],
            },
        ),
    ]
