# Generated by Django 5.1.6 on 2026-09-01 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OIDCInstelling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actief', models.BooleanField(default=False)),
                ('knop_label', models.CharField(default='Inloggen met SSO', max_length=64)),
                ('discovery_url', models.URLField(blank=True, default='', help_text='Issuer-URL of volledige .well-known/openid-configuration-URL.', max_length=500)),
                ('client_id', models.CharField(blank=True, default='', max_length=255)),
                ('client_secret_versleuteld', models.CharField(blank=True, default='', max_length=1024)),
                ('scopes', models.CharField(default='openid email profile', max_length=255)),
                ('claim_gebruikersnaam', models.CharField(default='preferred_username', max_length=64)),
                ('claim_email', models.CharField(default='email', max_length=64)),
                ('claim_groepen', models.CharField(default='groups', max_length=64)),
                ('groep_beheerders', models.CharField(blank=True, default='', help_text='Leden van deze IdP-groep worden beheerder (volledige rechten).', max_length=255)),
                ('gebruikers_aanmaken', models.BooleanField(default=True, help_text='Onbekende gebruikers automatisch aanmaken bij een geslaagde SSO-login.')),
                ('gewijzigd_op', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SSO-instelling',
                'verbose_name_plural': 'SSO-instellingen',
            },
        ),
        migrations.CreateModel(
            name='Gebruikersprofiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totp_geheim_versleuteld', models.CharField(blank=True, default='', max_length=255)),
                ('mfa_ingesteld', models.BooleanField(default=False, help_text='Heeft de gebruiker een authenticator-app gekoppeld?')),
                ('via_sso', models.BooleanField(default=False, help_text='Aangemaakt via de identity provider. MFA wordt dan door de IdP afgedwongen.')),
                ('laatste_login', models.DateTimeField(blank=True, null=True)),
                ('laatste_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('gebruiker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profiel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'gebruikersprofiel',
                'verbose_name_plural': 'gebruikersprofielen',
            },
        ),
        migrations.CreateModel(
            name='ComponentToegang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(help_text="Sleutel uit de componentregistry, bijvoorbeeld 'openzaak'.", max_length=64)),
                ('niveau', models.CharField(choices=[('geen', 'Geen toegang'), ('lezen', 'Alleen lezen'), ('schrijven', 'Lezen en wijzigen')], default='lezen', max_length=16)),
                ('gebruiker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='component_rechten', to=settings.AUTH_USER_MODEL)),
                ('groep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='component_rechten', to='auth.group')),
            ],
            options={
                'verbose_name': 'componenttoegang',
                'verbose_name_plural': 'componenttoegang',
                'constraints': [models.UniqueConstraint(condition=models.Q(('gebruiker__isnull', False)), fields=('gebruiker', 'component'), name='uniek_recht_per_gebruiker_component'), models.UniqueConstraint(condition=models.Q(('groep__isnull', False)), fields=('groep', 'component'), name='uniek_recht_per_groep_component'), models.CheckConstraint(condition=models.Q(models.Q(('gebruiker__isnull', False), ('groep__isnull', True)), models.Q(('gebruiker__isnull', True), ('groep__isnull', False)), _connector='OR'), name='recht_hoort_bij_gebruiker_of_groep')],
            },
        ),
    ]
