# Generated by Django 5.2.17 on 2026-09-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toegang', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gebruikersprofiel',
            name='demo',
            field=models.BooleanField(default=False, help_text='Demo-account: mag alle componenten inzien maar niets wijzigen. Aan- en uit te zetten door een beheerder.'),
        ),
    ]
